// 300 palavras mais usadas do inglês, divididas em 10 dias de 30.
// Formato: [inglês, português, exemplo em inglês, exemplo em português]
// A ordem importa: as palavras 1-30 são o Dia 1, 31-60 o Dia 2, e assim por diante.

const WORDS = [
  // ---------- DIA 1: as palavras que aparecem em quase toda frase ----------
  ["the", "o, a, os, as", "The sun is hot.", "O sol está quente."],
  ["be", "ser, estar", "I want to be happy.", "Eu quero ser feliz."],
  ["to", "para, a", "I go to school.", "Eu vou para a escola."],
  ["of", "de", "A cup of coffee.", "Uma xícara de café."],
  ["and", "e", "You and me.", "Você e eu."],
  ["a", "um, uma", "I have a car.", "Eu tenho um carro."],
  ["in", "em, dentro de", "She is in the kitchen.", "Ela está na cozinha."],
  ["that", "que, aquele, isso", "That is my book.", "Aquele é o meu livro."],
  ["have", "ter", "I have two cats.", "Eu tenho dois gatos."],
  ["I", "eu", "I am a student.", "Eu sou estudante."],
  ["it", "ele, ela (coisa), isso", "It is cold today.", "Está frio hoje."],
  ["for", "para, por", "This is for you.", "Isto é para você."],
  ["not", "não", "I am not tired.", "Eu não estou cansado."],
  ["on", "em cima de, sobre", "The book is on the table.", "O livro está sobre a mesa."],
  ["with", "com", "Come with me.", "Venha comigo."],
  ["he", "ele", "He is my friend.", "Ele é meu amigo."],
  ["as", "como, enquanto", "She works as a teacher.", "Ela trabalha como professora."],
  ["you", "você, vocês", "You are nice.", "Você é legal."],
  ["do", "fazer", "What do you do?", "O que você faz?"],
  ["at", "em, às", "See you at five.", "Te vejo às cinco."],
  ["this", "este, esta, isto", "This is my house.", "Esta é a minha casa."],
  ["but", "mas", "I am tired, but happy.", "Estou cansado, mas feliz."],
  ["his", "dele", "This is his car.", "Este é o carro dele."],
  ["by", "por, de (autor)", "A song by my favorite band.", "Uma música da minha banda favorita."],
  ["from", "de (origem)", "I am from Brazil.", "Eu sou do Brasil."],
  ["they", "eles, elas", "They are at the beach.", "Eles estão na praia."],
  ["we", "nós", "We are friends.", "Nós somos amigos."],
  ["say", "dizer", "Say hello to her.", "Diga oi para ela."],
  ["her", "dela, a ela", "I like her dress.", "Eu gosto do vestido dela."],
  ["she", "ela", "She is very smart.", "Ela é muito inteligente."],

  // ---------- DIA 2: perguntas e ligações entre ideias ----------
  ["or", "ou", "Tea or coffee?", "Chá ou café?"],
  ["an", "um, uma (antes de vogal)", "I eat an apple.", "Eu como uma maçã."],
  ["will", "(futuro) vai, irá", "I will call you.", "Eu vou te ligar."],
  ["my", "meu, minha", "My name is Ana.", "Meu nome é Ana."],
  ["one", "um (número)", "I have one brother.", "Eu tenho um irmão."],
  ["all", "todo, todos", "All my friends are here.", "Todos os meus amigos estão aqui."],
  ["would", "(condicional) -ria", "I would like some water.", "Eu gostaria de um pouco de água."],
  ["there", "lá, ali; há", "There is a park near my house.", "Há um parque perto da minha casa."],
  ["their", "deles, delas", "Their dog is big.", "O cachorro deles é grande."],
  ["what", "o que, qual", "What is your name?", "Qual é o seu nome?"],
  ["so", "então, tão", "I was tired, so I slept.", "Eu estava cansado, então dormi."],
  ["up", "para cima", "Stand up, please.", "Levante-se, por favor."],
  ["out", "fora, para fora", "Get out of the car.", "Saia do carro."],
  ["if", "se", "If it rains, I stay home.", "Se chover, eu fico em casa."],
  ["about", "sobre, cerca de", "Tell me about you.", "Me fale sobre você."],
  ["who", "quem", "Who is she?", "Quem é ela?"],
  ["get", "conseguir, pegar, receber", "I get a lot of emails.", "Eu recebo muitos e-mails."],
  ["which", "qual, que", "Which color do you like?", "De qual cor você gosta?"],
  ["go", "ir", "Let's go to the beach.", "Vamos à praia."],
  ["me", "me, mim", "Call me later.", "Me liga mais tarde."],
  ["when", "quando", "When is your birthday?", "Quando é o seu aniversário?"],
  ["make", "fazer, criar", "I make dinner every day.", "Eu faço o jantar todo dia."],
  ["can", "poder, conseguir", "I can swim.", "Eu sei nadar."],
  ["like", "gostar; como", "I like pizza.", "Eu gosto de pizza."],
  ["time", "tempo, vez, hora", "What time is it?", "Que horas são?"],
  ["no", "não, nenhum", "No, thank you.", "Não, obrigado."],
  ["just", "apenas, só; acabou de", "I just want to rest.", "Eu só quero descansar."],
  ["him", "ele, o, lhe", "I miss him.", "Eu sinto falta dele."],
  ["know", "saber, conhecer", "I know her.", "Eu a conheço."],
  ["take", "pegar, levar", "Take your umbrella.", "Leve seu guarda-chuva."],

  // ---------- DIA 3: pessoas, tempo e jeito de fazer ----------
  ["people", "pessoas", "Many people live here.", "Muitas pessoas moram aqui."],
  ["into", "para dentro de", "She went into the room.", "Ela entrou na sala."],
  ["year", "ano", "I am twenty years old.", "Eu tenho vinte anos."],
  ["your", "seu, sua (de você)", "Is this your bag?", "Esta é a sua bolsa?"],
  ["good", "bom, boa", "Good morning!", "Bom dia!"],
  ["some", "algum, alguns, um pouco", "I want some rice.", "Eu quero um pouco de arroz."],
  ["could", "podia, poderia", "Could you help me?", "Você poderia me ajudar?"],
  ["them", "eles, os, as, lhes", "I see them every day.", "Eu os vejo todo dia."],
  ["see", "ver", "I see a bird.", "Eu vejo um pássaro."],
  ["other", "outro, outra", "The other shoe is here.", "O outro sapato está aqui."],
  ["than", "do que", "He is taller than me.", "Ele é mais alto do que eu."],
  ["then", "então, depois", "Eat first, then sleep.", "Coma primeiro, depois durma."],
  ["now", "agora", "I am busy now.", "Estou ocupado agora."],
  ["look", "olhar, parecer", "Look at the sky!", "Olhe para o céu!"],
  ["only", "só, apenas, único", "I have only one pen.", "Eu tenho só uma caneta."],
  ["come", "vir", "Come here!", "Venha aqui!"],
  ["its", "seu, sua (de coisa ou animal)", "The dog wants its food.", "O cachorro quer a comida dele."],
  ["over", "sobre, acima; acabado", "The game is over.", "O jogo acabou."],
  ["think", "pensar, achar", "I think you are right.", "Eu acho que você está certo."],
  ["also", "também", "I also speak Spanish.", "Eu também falo espanhol."],
  ["back", "de volta; costas", "I will be back soon.", "Eu volto logo."],
  ["after", "depois de", "After lunch, I work.", "Depois do almoço, eu trabalho."],
  ["use", "usar", "Can I use your pen?", "Posso usar sua caneta?"],
  ["two", "dois, duas", "I have two sisters.", "Eu tenho duas irmãs."],
  ["how", "como", "How are you?", "Como você está?"],
  ["our", "nosso, nossa", "This is our car.", "Este é o nosso carro."],
  ["work", "trabalhar; trabalho", "I work from home.", "Eu trabalho de casa."],
  ["first", "primeiro", "This is my first day.", "Este é o meu primeiro dia."],
  ["well", "bem", "I sleep well.", "Eu durmo bem."],
  ["way", "caminho, jeito", "This is the way to the park.", "Este é o caminho para o parque."],

  // ---------- DIA 4: o verbo "to be", quantidades e perguntas ----------
  ["even", "até, mesmo", "Even kids know this.", "Até as crianças sabem isso."],
  ["new", "novo, nova", "I have a new job.", "Eu tenho um emprego novo."],
  ["want", "querer", "I want ice cream.", "Eu quero sorvete."],
  ["because", "porque", "I eat because I am hungry.", "Eu como porque estou com fome."],
  ["any", "algum, qualquer, nenhum", "Do you have any questions?", "Você tem alguma pergunta?"],
  ["these", "estes, estas", "These shoes are new.", "Estes sapatos são novos."],
  ["give", "dar", "Give me the key.", "Me dê a chave."],
  ["day", "dia", "Have a nice day!", "Tenha um bom dia!"],
  ["most", "a maioria, o mais", "Most people like music.", "A maioria das pessoas gosta de música."],
  ["us", "nós, nos", "Help us, please.", "Nos ajude, por favor."],
  ["is", "é, está (ele, ela)", "She is a doctor.", "Ela é médica."],
  ["are", "são, estão; é, está (você)", "We are ready.", "Nós estamos prontos."],
  ["was", "era, estava, foi", "It was a good day.", "Foi um bom dia."],
  ["were", "eram, estavam, foram", "They were at the park.", "Eles estavam no parque."],
  ["has", "tem (ele, ela)", "He has a big dog.", "Ele tem um cachorro grande."],
  ["had", "tinha, teve", "I had a dream.", "Eu tive um sonho."],
  ["very", "muito", "It is very hot.", "Está muito quente."],
  ["where", "onde", "Where do you live?", "Onde você mora?"],
  ["why", "por que", "Why are you late?", "Por que você está atrasado?"],
  ["here", "aqui", "Wait here.", "Espere aqui."],
  ["much", "muito (para o que não se conta)", "Thank you very much!", "Muito obrigado!"],
  ["many", "muitos, muitas", "I have many friends.", "Eu tenho muitos amigos."],
  ["more", "mais", "I want more juice.", "Eu quero mais suco."],
  ["thing", "coisa", "This thing is strange.", "Esta coisa é estranha."],
  ["man", "homem", "That man is my uncle.", "Aquele homem é meu tio."],
  ["woman", "mulher", "The woman is singing.", "A mulher está cantando."],
  ["child", "criança, filho(a)", "The child is playing.", "A criança está brincando."],
  ["life", "vida", "Life is beautiful.", "A vida é bela."],
  ["world", "mundo", "I want to see the world.", "Eu quero conhecer o mundo."],
  ["school", "escola", "My school is near.", "Minha escola é perto."],

  // ---------- DIA 5: coisas do dia a dia ----------
  ["family", "família", "I love my family.", "Eu amo minha família."],
  ["friend", "amigo, amiga", "She is my best friend.", "Ela é minha melhor amiga."],
  ["house", "casa (construção)", "The house is white.", "A casa é branca."],
  ["home", "lar, casa", "I am going home.", "Eu estou indo para casa."],
  ["water", "água", "I drink water.", "Eu bebo água."],
  ["food", "comida", "The food is good.", "A comida é boa."],
  ["money", "dinheiro", "I need money.", "Eu preciso de dinheiro."],
  ["car", "carro", "My car is red.", "Meu carro é vermelho."],
  ["book", "livro", "I read a book.", "Eu leio um livro."],
  ["name", "nome", "What is his name?", "Qual é o nome dele?"],
  ["hand", "mão", "Wash your hands.", "Lave as mãos."],
  ["eye", "olho", "She has blue eyes.", "Ela tem olhos azuis."],
  ["head", "cabeça", "My head hurts.", "Minha cabeça dói."],
  ["night", "noite", "Good night!", "Boa noite!"],
  ["morning", "manhã", "I run in the morning.", "Eu corro de manhã."],
  ["week", "semana", "See you next week.", "Até a semana que vem."],
  ["month", "mês", "I travel every month.", "Eu viajo todo mês."],
  ["city", "cidade", "The city is big.", "A cidade é grande."],
  ["country", "país; campo", "Brazil is a big country.", "O Brasil é um país grande."],
  ["job", "emprego, trabalho", "I love my job.", "Eu amo o meu trabalho."],
  ["place", "lugar", "This is a nice place.", "Este é um lugar legal."],
  ["part", "parte", "This is the best part.", "Esta é a melhor parte."],
  ["number", "número", "What is your phone number?", "Qual é o seu número de telefone?"],
  ["word", "palavra", "Learn a new word.", "Aprenda uma palavra nova."],
  ["question", "pergunta", "Can I ask a question?", "Posso fazer uma pergunta?"],
  ["problem", "problema", "No problem!", "Sem problema!"],
  ["story", "história", "Tell me a story.", "Me conte uma história."],
  ["idea", "ideia", "Good idea!", "Boa ideia!"],
  ["door", "porta", "Close the door.", "Feche a porta."],
  ["room", "quarto, sala", "My room is small.", "Meu quarto é pequeno."],

  // ---------- DIA 6: verbos de ação (parte 1) ----------
  ["find", "encontrar, achar", "I can't find my keys.", "Não consigo achar minhas chaves."],
  ["tell", "contar, dizer", "Tell me the truth.", "Me conte a verdade."],
  ["ask", "perguntar, pedir", "Ask the teacher.", "Pergunte ao professor."],
  ["feel", "sentir", "I feel good today.", "Eu me sinto bem hoje."],
  ["try", "tentar, experimentar", "Try again!", "Tente de novo!"],
  ["leave", "sair, deixar", "I leave at six.", "Eu saio às seis."],
  ["call", "ligar, chamar", "Call me tonight.", "Me liga hoje à noite."],
  ["need", "precisar", "I need help.", "Eu preciso de ajuda."],
  ["become", "tornar-se", "I want to become a doctor.", "Eu quero me tornar médico."],
  ["keep", "manter, guardar", "Keep the change.", "Fique com o troco."],
  ["let", "deixar, permitir", "Let me help you.", "Deixa eu te ajudar."],
  ["begin", "começar", "The class begins at eight.", "A aula começa às oito."],
  ["help", "ajudar; ajuda", "Can you help me?", "Você pode me ajudar?"],
  ["talk", "conversar, falar", "Let's talk later.", "Vamos conversar depois."],
  ["turn", "virar; vez", "Turn left here.", "Vire à esquerda aqui."],
  ["start", "começar, ligar", "Start the car.", "Ligue o carro."],
  ["show", "mostrar", "Show me your photo.", "Me mostre sua foto."],
  ["hear", "ouvir", "I hear music.", "Eu ouço música."],
  ["play", "jogar, brincar, tocar", "Let's play soccer.", "Vamos jogar futebol."],
  ["run", "correr", "I run every day.", "Eu corro todo dia."],
  ["move", "mover, mudar-se", "We move next month.", "Nós nos mudamos mês que vem."],
  ["live", "morar, viver", "I live in a big city.", "Eu moro em uma cidade grande."],
  ["believe", "acreditar", "I believe you.", "Eu acredito em você."],
  ["bring", "trazer", "Bring your friends.", "Traga seus amigos."],
  ["happen", "acontecer", "What happened?", "O que aconteceu?"],
  ["write", "escrever", "Write your name here.", "Escreva seu nome aqui."],
  ["sit", "sentar", "Sit down, please.", "Sente-se, por favor."],
  ["stand", "ficar de pé", "Please stand in line.", "Por favor, fique na fila."],
  ["lose", "perder", "Don't lose your ticket.", "Não perca seu ingresso."],
  ["pay", "pagar", "I pay the bill.", "Eu pago a conta."],

  // ---------- DIA 7: verbos de ação (parte 2) ----------
  ["meet", "conhecer, encontrar", "Nice to meet you!", "Prazer em te conhecer!"],
  ["learn", "aprender", "I learn English every day.", "Eu aprendo inglês todo dia."],
  ["change", "mudar, trocar; troco", "People change.", "As pessoas mudam."],
  ["understand", "entender", "I don't understand.", "Eu não entendo."],
  ["watch", "assistir; relógio", "I watch TV at night.", "Eu assisto TV à noite."],
  ["follow", "seguir", "Follow me.", "Me siga."],
  ["stop", "parar", "Stop the car!", "Pare o carro!"],
  ["speak", "falar (um idioma)", "Do you speak English?", "Você fala inglês?"],
  ["read", "ler", "I read the news.", "Eu leio as notícias."],
  ["open", "abrir; aberto", "Open the window.", "Abra a janela."],
  ["close", "fechar; perto", "Close your eyes.", "Feche os olhos."],
  ["eat", "comer", "Let's eat!", "Vamos comer!"],
  ["drink", "beber; bebida", "Drink more water.", "Beba mais água."],
  ["sleep", "dormir; sono", "I sleep at ten.", "Eu durmo às dez."],
  ["buy", "comprar", "I want to buy shoes.", "Eu quero comprar sapatos."],
  ["sell", "vender", "They sell fruit.", "Eles vendem frutas."],
  ["love", "amar; amor", "I love you.", "Eu te amo."],
  ["wait", "esperar", "Wait for me!", "Me espere!"],
  ["walk", "andar, caminhar", "I walk to work.", "Eu vou a pé para o trabalho."],
  ["remember", "lembrar", "I remember you.", "Eu me lembro de você."],
  ["forget", "esquecer", "Don't forget your bag.", "Não esqueça sua bolsa."],
  ["send", "enviar, mandar", "Send me a message.", "Me mande uma mensagem."],
  ["build", "construir", "They build houses.", "Eles constroem casas."],
  ["stay", "ficar, permanecer", "Stay with me.", "Fique comigo."],
  ["fall", "cair; outono", "Be careful, don't fall!", "Cuidado, não caia!"],
  ["cut", "cortar", "Cut the bread.", "Corte o pão."],
  ["win", "ganhar, vencer", "We want to win.", "Nós queremos vencer."],
  ["grow", "crescer, cultivar", "Children grow fast.", "As crianças crescem rápido."],
  ["carry", "carregar", "I carry my bag.", "Eu carrego minha bolsa."],
  ["put", "colocar, pôr", "Put it on the table.", "Coloque na mesa."],

  // ---------- DIA 8: como as coisas são (adjetivos) ----------
  ["big", "grande", "A big house.", "Uma casa grande."],
  ["small", "pequeno", "A small dog.", "Um cachorro pequeno."],
  ["long", "longo, comprido", "She has long hair.", "Ela tem cabelo comprido."],
  ["short", "curto, baixo", "The movie is short.", "O filme é curto."],
  ["great", "ótimo, grande", "That's great!", "Que ótimo!"],
  ["little", "pequeno; pouco", "A little cat.", "Um gatinho."],
  ["old", "velho, antigo", "My phone is old.", "Meu celular é velho."],
  ["young", "jovem", "He is very young.", "Ele é muito jovem."],
  ["high", "alto (altura)", "The wall is high.", "O muro é alto."],
  ["low", "baixo", "The price is low.", "O preço está baixo."],
  ["right", "certo; direita", "You are right.", "Você está certo."],
  ["wrong", "errado", "This is wrong.", "Isto está errado."],
  ["same", "mesmo, igual", "We have the same shoes.", "Nós temos os mesmos sapatos."],
  ["different", "diferente", "We are very different.", "Nós somos muito diferentes."],
  ["important", "importante", "This is important.", "Isto é importante."],
  ["bad", "ruim, mau", "It was a bad day.", "Foi um dia ruim."],
  ["better", "melhor (comparando)", "I feel better now.", "Eu me sinto melhor agora."],
  ["best", "o melhor", "You are the best!", "Você é o melhor!"],
  ["easy", "fácil", "English is easy.", "Inglês é fácil."],
  ["hard", "difícil; duro", "The test was hard.", "A prova foi difícil."],
  ["happy", "feliz", "I am happy today.", "Eu estou feliz hoje."],
  ["sad", "triste", "The movie is sad.", "O filme é triste."],
  ["hot", "quente", "The coffee is hot.", "O café está quente."],
  ["cold", "frio", "The water is cold.", "A água está fria."],
  ["beautiful", "bonito, lindo", "What a beautiful day!", "Que dia lindo!"],
  ["next", "próximo", "See you next time.", "Até a próxima."],
  ["last", "último; passado", "This is the last one.", "Este é o último."],
  ["few", "poucos", "Few people came.", "Poucas pessoas vieram."],
  ["own", "próprio", "I have my own room.", "Eu tenho meu próprio quarto."],
  ["sure", "certo, claro", "Sure, no problem!", "Claro, sem problema!"],

  // ---------- DIA 9: quando, onde e quanto ----------
  ["always", "sempre", "I always drink coffee.", "Eu sempre bebo café."],
  ["never", "nunca", "I never smoke.", "Eu nunca fumo."],
  ["sometimes", "às vezes", "Sometimes I cook.", "Às vezes eu cozinho."],
  ["often", "frequentemente", "I often read at night.", "Eu leio à noite com frequência."],
  ["today", "hoje", "Today is Monday.", "Hoje é segunda-feira."],
  ["tomorrow", "amanhã", "See you tomorrow!", "Até amanhã!"],
  ["yesterday", "ontem", "I was sick yesterday.", "Eu estava doente ontem."],
  ["again", "de novo, novamente", "Say it again.", "Diga de novo."],
  ["still", "ainda", "I still love you.", "Eu ainda te amo."],
  ["already", "já", "I already ate.", "Eu já comi."],
  ["before", "antes", "Wash your hands before eating.", "Lave as mãos antes de comer."],
  ["between", "entre", "The bank is between two stores.", "O banco fica entre duas lojas."],
  ["under", "embaixo de, sob", "The cat is under the bed.", "O gato está embaixo da cama."],
  ["through", "através de, por", "We walk through the park.", "Nós caminhamos pelo parque."],
  ["during", "durante", "Don't talk during the class.", "Não fale durante a aula."],
  ["without", "sem", "Coffee without sugar.", "Café sem açúcar."],
  ["around", "ao redor, por aí", "Look around.", "Olhe ao redor."],
  ["down", "para baixo", "Go down the stairs.", "Desça a escada."],
  ["off", "desligado; fora", "Turn off the light.", "Desligue a luz."],
  ["too", "também; demais", "Me too!", "Eu também!"],
  ["really", "realmente, mesmo", "I really like it.", "Eu gosto muito disso."],
  ["maybe", "talvez", "Maybe tomorrow.", "Talvez amanhã."],
  ["together", "juntos", "Let's go together.", "Vamos juntos."],
  ["each", "cada", "Each student has a book.", "Cada aluno tem um livro."],
  ["every", "todo, toda (cada um)", "I run every morning.", "Eu corro toda manhã."],
  ["both", "ambos, os dois", "I like both.", "Eu gosto dos dois."],
  ["another", "outro (mais um)", "Another coffee, please.", "Outro café, por favor."],
  ["something", "algo, alguma coisa", "I want something sweet.", "Eu quero algo doce."],
  ["nothing", "nada", "I have nothing to do.", "Eu não tenho nada para fazer."],
  ["everything", "tudo", "Everything is fine.", "Está tudo bem."],

  // ---------- DIA 10: conversa básica e o mundo ao redor ----------
  ["yes", "sim", "Yes, I can.", "Sim, eu posso."],
  ["please", "por favor", "Water, please.", "Água, por favor."],
  ["thanks", "obrigado, obrigada", "Thanks for your help.", "Obrigado pela ajuda."],
  ["sorry", "desculpe", "Sorry, I am late.", "Desculpe, estou atrasado."],
  ["hello", "olá, oi", "Hello, how are you?", "Olá, como vai?"],
  ["goodbye", "tchau, adeus", "Goodbye, see you soon!", "Tchau, até logo!"],
  ["mother", "mãe", "My mother is a teacher.", "Minha mãe é professora."],
  ["father", "pai", "My father cooks well.", "Meu pai cozinha bem."],
  ["brother", "irmão", "My brother is ten.", "Meu irmão tem dez anos."],
  ["sister", "irmã", "My sister lives in London.", "Minha irmã mora em Londres."],
  ["boy", "menino", "The boy is running.", "O menino está correndo."],
  ["girl", "menina", "The girl is reading.", "A menina está lendo."],
  ["person", "pessoa", "She is a good person.", "Ela é uma boa pessoa."],
  ["body", "corpo", "Exercise is good for the body.", "Exercício faz bem para o corpo."],
  ["heart", "coração", "My heart is beating fast.", "Meu coração está batendo rápido."],
  ["sun", "sol", "The sun is shining.", "O sol está brilhando."],
  ["street", "rua", "I live on this street.", "Eu moro nesta rua."],
  ["store", "loja", "The store is closed.", "A loja está fechada."],
  ["table", "mesa", "The food is on the table.", "A comida está na mesa."],
  ["phone", "telefone, celular", "Where is my phone?", "Cadê meu celular?"],
  ["computer", "computador", "I work on my computer.", "Eu trabalho no meu computador."],
  ["music", "música", "I love music.", "Eu amo música."],
  ["game", "jogo", "This game is fun.", "Este jogo é divertido."],
  ["color", "cor", "Blue is my favorite color.", "Azul é a minha cor favorita."],
  ["coffee", "café", "I drink coffee every morning.", "Eu bebo café toda manhã."],
  ["hour", "hora", "The trip takes one hour.", "A viagem leva uma hora."],
  ["minute", "minuto", "Wait a minute!", "Espere um minuto!"],
  ["afternoon", "tarde", "Good afternoon!", "Boa tarde!"],
  ["breakfast", "café da manhã", "Breakfast is ready.", "O café da manhã está pronto."],
  ["office", "escritório", "The office is on the second floor.", "O escritório fica no segundo andar."],
];

const WORD_THEMES = [
  "Palavras que aparecem em quase toda frase",
  "Perguntas e ligações entre ideias",
  "Pessoas, tempo e jeito de fazer",
  "O verbo to be, quantidades e perguntas",
  "Coisas do dia a dia",
  "Verbos de ação, parte 1",
  "Verbos de ação, parte 2",
  "Como as coisas são",
  "Quando, onde e quanto",
  "Conversa básica e o mundo ao redor",
];
